avanzosc/odoo-addons

- crm_claim_sequence/README.rst
- crm_claim_sequence/__init__.py
- crm_claim_sequence/__openerp__.py
- crm_claim_sequence/data/claim_sequence.xml
- crm_claim_sequence/i18n/es.po
- crm_claim_sequence/models/__init__.py
- crm_claim_sequence/models/crm_claim.py
- crm_claim_sequence/views/crm_claim_view.xml
Módulo modificado a petición de Ana en issue https://github.com/odoomrp/odoomrp-utils/issues/18#issuecomment-72687593
> [IMP crm_claim_sequence]

- .travis.yml~
- sale_invoice_group/__init__.py
- sale_invoice_group/__openerp__.py
- sale_invoice_group/i18n/es.po
- sale_invoice_group/models/__init__.py
- sale_invoice_group/models/account_invoice_group.py
- sale_invoice_group/models/res_partner_invoicing_group.py
- sale_invoice_group/models/stock_picking.py
- sale_invoice_group/security/ir.model.access.csv
- sale_invoice_group/views/account_invoice_group_view.xml
- sale_invoice_group/views/res_partner_invoicing_group_view.xml
- sale_invoice_group/views/stock_picking_view.xml
Módulo que gestiona el tiempo que debe transcurrir desde la emisión del albarán a la facturación de la misma.
> [ADD] sale_invoice_group

- stock_visible_cost/README.rst
- stock_visible_cost/__init__.py
- stock_visible_cost/__openerp__.py
- stock_visible_cost/models/__init__.py
- stock_visible_cost/models/res_config.py
- stock_visible_cost/security/stock_visible_cost_security.xml
- stock_visible_cost/views/res_config_view.xml
- stock_visible_cost/views/stock_view.xml
> [ADD] New module <stock_visible_cost>

- .travis.yml
- mrp_bom_structure_show_child_with_manual_standard_cost/README.rst
- mrp_bom_structure_show_child_with_manual_standard_cost/__init__.py
- mrp_bom_structure_show_child_with_manual_standard_cost/__openerp__.py
- mrp_bom_structure_show_child_with_manual_standard_cost/i18n/es.po
- mrp_bom_structure_show_child_with_manual_standard_cost/i18n/mrp_bom_structure_show_child_with_manual_standard_cost.pot
- mrp_bom_structure_show_child_with_manual_standard_cost/models/__init__.py
- mrp_bom_structure_show_child_with_manual_standard_cost/models/mrp_bom_line.py
- mrp_bom_structure_show_child_with_manual_standard_cost/views/mrp_bom_line_structure_view.xml
Nuevo módulo para mostrar el coste standard de los hijos de la lista de materiales
> [ADD] mrp_bom_structure_show_child_with_manual_standard_cost.

- product_supplierinfo_expand_view/README.rst
- product_supplierinfo_expand_view/__init__.py
- product_supplierinfo_expand_view/__openerp__.py
- product_supplierinfo_expand_view/models/__init__.py
- product_supplierinfo_expand_view/models/product_supplierinfo.py
- product_supplierinfo_expand_view/views/product_supplierinfo_view.xml
Allow to view some fields of product_supplierinfo in tree view.
> [ADD] product_supplierinfo_expand_view

- crm_claim_filter/README.rst
- crm_claim_filter/__init__.py
- crm_claim_filter/__openerp__.py
- crm_claim_filter/i18n/es.po
- crm_claim_filter/models/__init__.py
- crm_claim_filter/models/crm_claim.py
- crm_claim_filter/tests/__init__.py
- crm_claim_filter/tests/test_crm_claim_filter.py
- crm_claim_filter/views/crm_claim_view.xml
Nuevo módulo para extender el filtro de reclamaciones.
> [ADD] crm_claim_filter: Extend claim filters

- crm_claim_close/README.rst
- crm_claim_close/__init__.py
- crm_claim_close/__openerp__.py
- crm_claim_close/models/__init__.py
- crm_claim_close/models/crm_claim.py
- crm_claim_close/tests/__init__.py
- crm_claim_close/tests/test_crm_claim_close.py
- crm_claim_close/views/crm_claim_view.xml
Requieren que esté visible el campo fecha de creación (si no lo está ya)
Además, requieren un campo "fecha cierre" y un botón de "cerrar" reclamación
> [ADD] New module crm_claim_close

- crm_claim_company/README.rst
- crm_claim_company/__init__.py
- crm_claim_company/__openerp__.py
- crm_claim_company/i18n/es.po
- crm_claim_company/views/crm_claim_view.xml
Nuevo módulo para mostrar la compañia en reclamaciones.
> [ADD] crm_claim_company: Show company in claims.

- pesa_custom/README.rst
- pesa_custom/__init__.py
- pesa_custom/__openerp__.py
- pesa_custom/i18n/es.po
- pesa_custom/models/__init__.py
- pesa_custom/models/crm_claim.py
- pesa_custom/models/real_line.py
- pesa_custom/models/schedule.py
- pesa_custom/models/trajectory.py
- pesa_custom/views/crm_claim_view.xml
- pesa_custom/views/schedule_view.xml
Solicitan añadir los siguientes campos en la reclamación:
- Línea: Campo texto
- Línea real: Many2one a tabla maestra con un único campo "nombre"
- Trayecto: Many2one a tabla maestra con un único campo "nombre"
- Horario: Many2one a tabla maestra con un único campo de tipo "hora"
- Conductor: Añadir nuevo campo many2one a "usuario" 
- Num libro: Campo numérico
- Hoja libro: Campo numérico
> [ADD] New module pesa_custom

- customer_invoice_personalized_report/I18n/es.po
- customer_invoice_personalized_report/README.rst
- customer_invoice_personalized_report/__init__.py
- customer_invoice_personalized_report/__openerp__.py
- customer_invoice_personalized_report/report/report_customer_invoice_personalized.xml
- customer_invoice_personalized_report/views/customer_invoice_personalized_report.xml
- oca_dependencies.txt
- picking_a5_landscape_report/README.rst
- picking_a5_landscape_report/__init__.py
- picking_a5_landscape_report/__openerp__.py
- picking_a5_landscape_report/data/report_paperformat.xml
- picking_a5_landscape_report/i18n/es.po
- picking_a5_landscape_report/report/report_picking_a5_landscape.xml
- picking_a5_landscape_report/views/picking_a5_landscape_report.xml
- purchase_order_personalized_report/I18n/es.po
- purchase_order_personalized_report/README.rst
- purchase_order_personalized_report/__init__.py
- purchase_order_personalized_report/__openerp__.py
- purchase_order_personalized_report/report/report_purchase_order_personalized.xml
- purchase_order_personalized_report/views/purchase_order_personalized_report.xml
- sale_order_personalized_report/I18n/es.po
- sale_order_personalized_report/README.rst
- sale_order_personalized_report/__init__.py
- sale_order_personalized_report/__openerp__.py
- sale_order_personalized_report/report/report_sale_order_personalized.xml
- sale_order_personalized_report/views/sale_order_personalized_report.xml
[ADD] picking_a5_landscape_report: Personalized report.
[ADD] purchase_order_personalized_report: Personalized report.
[ADD] sale_order_personalized_report: Personalized report.
4 módulos nuevos para personalizar informes de pedido de venta, albaran de salida, pedido de compra, factura de cliente.
> [ADD] customer_invoice_personaliced_report: Personalized report.

- sale_order_create_event/README.rst
- sale_order_create_event/__init__.py
- sale_order_create_event/__openerp__.py
- sale_order_create_event/i18n/es.po
- sale_order_create_event/models/__init__.py
- sale_order_create_event/models/event_track.py
- sale_order_create_event/models/project_task.py
- sale_order_create_event/models/sale_order.py
- sale_order_create_event/tests/__init__.py
- sale_order_create_event/tests/test_sale_order_create_event.py
- sale_order_create_event/views/project_task_view.xml
Nuevo módulo para crear un evento automáticamente, cuando se confirma un pedido de venta.
> [ADD] sale_order_create_event: Create event when confirming sale order.

- crm_claim_team/__openerp__.py
- crm_claim_team/models/__init__.py
- crm_claim_team/models/crm_claim.py
- crm_claim_team/tests/test_crm_claim_team.py
- crm_claim_team/views/crm_claim_stage_view.xml
- crm_claim_team/views/crm_claim_view.xml
.- Onchange: Al asignar equipo en una reclamación, poner como responsable de la reclamación al jefe del equipo
.- Si una reclamación tiene un equipo asignado, el responsable debe ser filtrado para que solo te deje coger usuario que pertenezcan a ese equipo.
> [MOD] crm_claim_team

- project_events/tests/__init__.py
- project_events/tests/test_project_events.py
Módulo modificado para realizarle el test.
@oihane , @agaldona , @Daniel-CA , @esthermm ... 
¿le podéis echar un vistazo por favor?, es urgente.
Eskerik asko.
> [IMP] project_events: Make the test module.

- project_events_operations/__openerp__.py
- project_events_operations/i18n/es.po
- project_events_operations/tests/__init__.py
- project_events_operations/tests/test_project_events_operations.py
Poner como instalable el módulo, ponerle la antigüa dependencia, y realizarle los test.
> [IMP] project_events_operations: Make the test module.

- event_track_assistant/__openerp__.py
- event_track_assistant/i18n/es.po
- event_track_assistant/security/ir.model.access.csv
- event_track_assistant/wizard/wiz_event_append_assistant.py
- report_odoo_logo/__openerp__.py
- report_odoo_logo/security/ir.model.access.csv
[IMP] report_odoo_logo: Realize the security file
event_track_assistant --> Modificado para sacar código, y meterlo en funciones que luego serán reutilizadas, se ha hecho también el fichero "security" que hacía fallar a travis.
report_odoo_logo --> Modificado para realizarle el fichero "security", que hacía fallar a travis.
> [IMP] event_track_assistant: Take code and place in functions

- procurement_service_project/models/project_task.py
Modificado el formato a la hora de grabar fecha de incio y de fin de la tarea.
> [IMP] procurement_service_project: Modify project task date format.

- event_registration_analytic/tests/test_event_registration_analytic.py
- sale_order_line_attached_check/README.rst
- sale_order_line_attached_check/tests/test_sale_order_line_attached_check.py
Modificado el módulo por un error en travis
> [FIX] sale_order_line_attached_check: Fix error in test

- sale_order_create_event/i18n/es.po
- sale_order_create_event/models/sale_order.py
- sale_order_create_event/tests/test_sale_order_create_event.py
Meter 3 condiciones al confirmar pedido de venta.
> [IMP] sale_order_create_event: Put conditions to confirm sale_order.

- crm_claim_phonecall/models/crm_phonecall.py
- crm_claim_phonecall/tests/test_crm_claim_call.py
- crm_claim_phonecall/views/crm_claim_view.xml
- crm_claim_phonecall/views/crm_phonecall_view.xml
Arrastrar los datos del cliente al añadir una llamada a la reclamación
No crear las llamadas en estado realizado
> [MOD] crm_claim_phonecall

- crm_claim_phonecall/__openerp__.py
- crm_claim_phonecall/tests/test_crm_claim_call.py
- crm_claim_phonecall/wizard/__init__.py
- crm_claim_phonecall/wizard/crm_phonecall2phonecall.py
- crm_claim_phonecall/wizard/crm_phonecall_to_phonecall_view.xml
Al planificar una llamada, se lleve consigo el claim al que esta asociado
> [MOD] crm_claim_phonecall: schedule other call it goes with claim_id

- crm_claim_related/i18n/es.po
- crm_claim_related/models/crm_claim.py
- crm_claim_related/views/crm_claim_view.xml
Modificado el módulo para que se pueda ver en reclamaciones un many2many a reclamaciones.
> [IMP] crm_claim_related: View many2many in claims to claims.

- hr_contract_history/README.rst
- hr_contract_history/__init__.py
- hr_contract_history/__openerp__.py
- hr_contract_history/i18n/es.po
- hr_contract_history/models/__init__.py
- hr_contract_history/models/hr_contract.py
- hr_contract_history/security/ir.model.access.csv
- hr_contract_history/views/hr_contract_view.xml
- procurement_service_project/models/__init__.py
- procurement_service_project/models/stock_move.py
- project_events_operations/README.rst
- project_events_operations/__init__.py
- project_events_operations/__openerp__.py
- project_events_operations/tests/test_project_events_operations.py
- project_events_operations/wizard/__init__.py
- project_events_operations/wizard/events_copy.py
- project_events_operations/wizard/events_date_modify.py
- project_events_operations/wizard/events_timetable_unify.py
- purchase_order_search_extended/README.rst
- purchase_order_search_extended/__init__.py
- purchase_order_search_extended/__openerp__.py
- purchase_order_search_extended/i18n/es.po
- purchase_order_search_extended/views/purchase_order_view.xml
- sale_order_line_attached_check/tests/test_sale_order_line_attached_check.py
No crear "stock.move" para productos confirmados en pedidos de venta, de tipo servicio.
> [FIX] procurement_service_project: No create move for service product.

- crm_claim_security/README.rst
- crm_claim_security/__init__.py
- crm_claim_security/__openerp__.py
- crm_claim_security/security/crm_claim_security.xml
- crm_claim_security/security/ir.model.access.csv
- crm_claim_security/views/sale_view.xml
Ver todas las reclamaciones (See all Claims)
Ver reclamaciones de mi equipo y las que no están asignadas a ningún equipo, ni ningún responsable (See team claims) 
Ver las reclamaciones propias y las que no están asignadas a ningún responsable (See own and public claims)
Ver las reclamaciones propias ( own leads)
SOLO ver las reclamaciones propias (update own leads: igual que own leads pero no pueden crear nuevas)
> [ADD] crm_claim_security

- sale_order_line_service_view/models/sale_order.py
- sale_order_line_service_view/views/sale_order_view.xml
Mostrar el campo "order_line" de pedidos de venta, para poder borrar filas.
> [FIX] sale_order_line_service_view: Show order_line field.

- stock_inventory_line_ext/README.rst
- stock_inventory_line_ext/__init__.py
- stock_inventory_line_ext/__openerp__.py
- stock_inventory_line_ext/models/__init__.py
- stock_inventory_line_ext/models/stock.py
- stock_inventory_line_ext/tests/__init__.py
- stock_inventory_line_ext/tests/test_stock_inventory_line.py
- stock_inventory_line_ext/views/stock_inventory_view.xml
En líneas de inventario actualmente se necesita añadir los siguientes campos :
- campo de "COSTE":   relacionado con la ficha de producto.
- "VALOR": calculado cantidad x coste.
- "EN REPARACIÓN": calculado sumatorio de cantidad de las líneas de reparación en las que aparece dicho producto que este en reparación
- "CANT. NETO": calculado cantidad teórica menos nº de unidades en reparación.
- "VALOR NETO": cant. neto x coste
> [ADD] stock_inventory_line_ext: new module

- sale_order_line_service_view/__openerp__.py
- sale_order_line_service_view/i18n/es.po
- sale_order_line_service_view/tests/__init__.py
- sale_order_line_service_view/tests/test_sale_order_line_service_view.py
- sale_order_line_service_view/views/sale_order_view.xml
- sale_order_line_service_view/wizard/__init__.py
- sale_order_line_service_view/wizard/wiz_delete_sale_line.py
- sale_order_line_service_view/wizard/wiz_delete_sale_line_view.xml
Se ha creado un botón que llama a un wizard, para borrar líneas de pedido de venta.
> [IMP] sale_order_line_service_view: New wizard for delete lines.

- partner_student_course/README.rst
- partner_student_course/__init__.py
- partner_student_course/__openerp__.py
- partner_student_course/i18n/es.po
- partner_student_course/models/__init__.py
- partner_student_course/models/partner.py
- partner_student_course/models/partner_student_course.py
- partner_student_course/security/ir.model.access.csv
- partner_student_course/security/partner_student_course.xml
- partner_student_course/tests/__init__.py
- partner_student_course/tests/test_partner_student_course.py
- partner_student_course/views/partner_student_course_view.xml
- partner_student_course/views/res_partner_view.xml
Nuevo módulo que crea un objeto nuevo de "cursos estudiantes". 
En la ficha de partner, cuando se introduce la fecha de nacimiento, se cálcula automáticamente su curso.
> [ADD] partner_student_course: New module for define students courses.

- account_partner_payment_report/i18n/es.po
- account_partner_payment_report/report/report_partner_payment.py
- account_partner_payment_report/report/templates/report_partner_payment.mako
- account_partner_payment_report/wizard/wizard_partner_payment.py
- account_partner_payment_report/wizard/wizard_partner_payment_view.xml
- Cambiar funcionalidad check Permitir impagados
- Nuevo check Cobros a cuenta
- Agrupar por comercial y añadir saltos de página
> [IMP] account_partner_payment_report: modificaciones solicitadas por cliente

- product_supplierinfo_view/i18n/es.po
- product_supplierinfo_view/tests/__init__.py
- product_supplierinfo_view/tests/test_product_supplierinfo_view.py
- product_supplierinfo_view/views/product_supplierinfo_view.xml
- product_supplierinfo_view_variant/README.rst
- product_supplierinfo_view_variant/__init__.py
- product_supplierinfo_view_variant/__openerp__.py
- product_supplierinfo_view_variant/i18n/es.po
- product_supplierinfo_view_variant/views/product_supplierinfo_view.xml
+ new views to show product_tmpl_id
> [ADD] New module product_supplierinfo_view_variant glue module

- sale_order_line_annual_price/i18n/es.po
- sale_order_line_annual_price/views/sale_order_view.xml
- sale_order_line_performance/i18n/es.po
Cambiar literales de campos de líneas de pedido de venta.
> [IMP] sale_order_line_annual_price: Change fields literals.

- event_project_follower/__openerp__.py
- event_project_follower/models/event_event.py
- event_project_follower/tests/test_event_project_follower.py
create followers using method for that
> [IMP] event_project_follower: test with two users and
